
# mamba env create -f environment.yaml
# conda remove --name advtex --all -y

name: advtex

channels:
  - defaults
  - pytorch
  - conda-forge
  - bottler
  - pytorch3d

dependencies:
  - python=3.8

  - numpy=1.23.5
  - pandas=1.5.2
  - scipy=1.9.3
  - matplotlib=3.6.2
  - plotly=5.9.0
  - imageio=2.19.3
  - scikit-learn=1.2.0

  - pillow=9.3.0
  - tqdm=4.64.1
  - h5py=3.7.0

  - jupyterlab=3.5.2
  - conda-forge:jupyterlab_widgets=3.0.5

  - pytorch=1.10.0=py3.8_cuda11.3_cudnn8.2.0_0
  - cudatoolkit=11.3.1

  - conda-forge:setuptools=59.5.0
  - tensorboard=2.10.0
  - cmake=3.22.1

  - conda-forge:trimesh=3.16.4
  - conda-forge:flake8-comprehensions
  - conda-forge:flake8-bugbear
  - conda-forge:scikit-image=0.19.3 
  - conda-forge:dash-table=5.0.0 

  - joblib=1.1.1
  - lz4=3.1.3
  - pypng
  - plyfile=0.7.4
  - black=22.6.0
  - lpips=0.1.3
  - opt_einsum=3.3.0
  - line_profiler=3.3.1
  - yacs=0.1.6

  - gdown
  - pip

  - conda-forge:fvcore
  - conda-forge:iopath=0.1.9 
  #- bottler:nvidiacub=1.10.0
  - pytorch3d:pytorch3d=0.7.2=py38_cu113_pyt1100
  
  - pip:
    - isort==4.3.21
    - open3d==0.16.0
    - opencv-python==4.7.0.68
    - https://download.pytorch.org/whl/cu113/torchvision-0.11.1%2Bcu113-cp38-cp38-linux_x86_64.whl
