
# mamba env create -f environment.yaml
# conda remove --name advtex --all -y

name: advtex

channels:
  - defaults
  - pytorch
  - conda-forge
  - bottler
  - pytorch3d

dependencies:
  - python=3.8

  - numpy=1.23.5
  - pandas=1.5.2
  - scipy=1.9.3
  - matplotlib=3.6.2
  - plotly=5.9.0
  - imageio=2.19.3
  - scikit-learn=1.2.0

  - pillow=9.3.0
  - tqdm=4.64.1
  - h5py=3.7.0

  - jupyterlab=3.5.2
  - conda-forge:jupyterlab_widgets=3.0.5

  - pytorch=1.10.0=py3.8_cuda11.3_cudnn8.2.0_0
  #- pytorch:pytorch=1.9.1=py3.8_cuda11.1_cudnn8.0.5_0
  #- conda-forge:pytorch=1.9.1=cuda112py39h4e14dd4_3
  #- conda-forge:pytorch=1.9.1=cuda111py39hb4a4491_3
  #- conda-forge:pytorch=1.12.1=cuda112py38hd94e077_201

  #- cudatoolkit=11.1
  #- cudatoolkit=11.2.2
  #- cudatoolkit=11.6.0
  - cudatoolkit=11.3.1

  #- pytorch:torchvision=0.10.1=py38_cu111
  #- conda-forge:torchvision=0.10.1=py38cuda111he221d04_0_cuda
  #- conda-forge:torchvision=0.10.0=py38cuda111he221d04_0_cuda
  #- conda-forge:torchvision=0.9.1=py38cuda111he221d04_1_cuda
  #- torchvision=0.10=py38cuda112h04b465a_0_cuda
  #- torchvision

  - conda-forge:setuptools=59.5.0
  - tensorboard=2.10.0
  - cmake=3.22.1

  - conda-forge:trimesh=3.16.4
  - conda-forge:flake8-comprehensions
  - conda-forge:flake8-bugbear
  - conda-forge:scikit-image=0.19.3 
  - conda-forge:dash-table=5.0.0 

  #- conda-forge:opencv=4.6.0

  - joblib=1.1.1
  - lz4=3.1.3
  - pypng
  - plyfile=0.7.4
  - black=22.6.0
  - lpips=0.1.3
  - opt_einsum=3.3.0
  - line_profiler=3.3.1
  - yacs=0.1.6

  - gdown
  - pip

  # pytorch3d
  - conda-forge:fvcore
  - conda-forge:iopath=0.1.9 
  #- bottler:nvidiacub=1.10.0
  #- pytorch3d:pytorch3d=0.7.2=py38_cu111_pyt191
  #- pytorch3d:pytorch3d=0.7.2=py38_cu116_pyt1121
  - pytorch3d:pytorch3d=0.7.2=py38_cu113_pyt1100
  
  - pip:
    - isort==4.3.21
    - open3d==0.16.0
    - opencv-python==4.7.0.68
    - https://download.pytorch.org/whl/cu113/torchvision-0.11.1%2Bcu113-cp38-cp38-linux_x86_64.whl
  
  #   - 'isort<5'
  #   - lpips
  #   - trimesh
  #   - plotly
  #   - imageio
  #   - flake8-comprehensions
  #   - flake8
  #   - flake8-bugbear
  #   - scikit-image
  #   - pypng
  #   - plyfile
  #   - black
  #   - opt_einsum
  #   - line_profiler
  #   - yacs
  #   - opencv-python
